[package]
name = "wasm.bats-packages.dev/dom"
kind = "lib"
unsafe = false

[dependencies]
"wasm.bats-packages.dev/bridge" = ""
"array" = ""
"arith" = ""
"builder" = ""
"css" = ""
"str" = ""
"widget" = ""
